import '../styles/globals.css';

import Navigation from "./components/navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="es">
      <head>
        <title>Eventos</title>
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
